# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64400565dfde17df4a8fb8e4c1270f39c07aac428d31a4e3e31b7d0a362c51b7de01377e7f047c5b61370b4a82dee1f5a24c22332b1765ce25cc08d0dfb0f50b

test:
  secret_key_base: db413f25b84f4a3266a6273133b5f6bc9e9f1823fefb0e6a18a0c5c44faeac4204eac1752eaca48f5ec4a3463dd2f40d971ff85dac35c36e102cdacd0098166e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
